### ISSUE TITLE
Make sure that the index-store sync completely before "sync-complete-required" commands executing

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/ckb-cli#202]
```
bash devtools/ci/integration.sh v0.25.1
     Running `target/debug/cli-test --ckb-bin /home/ckb-cli-integration/ckb_v0.25.1_x86_64-unknown-linux-gnu/ckb --cli-bin /home/ckb-cli/target/release/ckb-cli`
[2019-12-04T06:48:05Z INFO  cli_test::util] [Execute]: /home/ckb-cli-integration/ckb_v0.25.1_x86_64-unknown-linux-gnu/ckb "-C /tmp/.tmprnvrTg init --chain dev --rpc-port 8114 --p2p-port 9114"
[2019-12-04T06:48:07Z INFO  cli_test::spec] [Execute]: dao deposit --privkey-path ./privkey --capacity 1103 --tx-fee 1
dao deposit: Capacity not enough: ckt1qyqvsv5240xeh85wvnau2eky8pwrhh4jr8ts8vyj37 => 0

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `73`,
 right: `66`: Capacity not enough: ckt1qyqvsv5240xeh85wvnau2eky8pwrhh4jr8ts8vyj37 => 0
', src/spec/dao.rs:21:9
stack backtrace:
   0:     0x5647e24dc7bb - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x5647e24dc7bb - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x5647e24dc7bb - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5647e24dc7bb - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5647e24dc7bb - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x5647e24dc496 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5647e24dcf2d - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5647e24dcab2 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x5647e24dc9ff - std::panicking::begin_panic_fmt::hc33ce01c7f7cd52d
                               at src/libstd/panicking.rs:339
   9:     0x5647e13e7510 - <cli_test::spec::dao::PrepareInFirstPeriod as cli_test::spec::Spec>::run::h84c47627836c5ea8
                               at src/spec/dao.rs:21
  10:     0x5647e13a4f12 - cli_test::run_spec::h7ee89005cf993642
                               at src/main.rs:97
  11:     0x5647e13a4769 - cli_test::main::h02cce07211e30b0f
                               at src/main.rs:57
  12:     0x5647e13c4840 - std::rt::lang_start::{{closure}}::h22d524cf69006697
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  13:     0x5647e24dc933 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  14:     0x5647e24dc933 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  15:     0x5647e24e4fda - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  16:     0x5647e24dd43d - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  17:     0x5647e24dd43d - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  18:     0x5647e24dd43d - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  19:     0x5647e13c4819 - std::rt::lang_start::hedc7a246c4fc3887
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  20:     0x5647e13a593a - main
  21:     0x7f969aeb7b97 - __libc_start_main
  22:     0x5647e139abaa - _start
  23:                0x0 - <unknown>
Makefile:16: recipe for target 'integration' failed
make: *** [integration] Error 101
```

It seems that the command executes before index-store synchronizing completely.

**Comment by keroro520** [comment]
https://github.com/nervosnetwork/ckb-cli/pull/204
