### ISSUE TITLE
`util completions zsh` panics again: Fatal internal error

### ISSUE THREAD

**Issue by dllud** [nervosnetwork/ckb-cli#551]
On ckb-cli 1.4.0 (7671237 2023-01-05) running `ckb-cli util completions zsh` still fails (it works for all other shells).

```
thread 'main' panicked at 'Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/clap_generate-3.0.0-beta.1/src/generators/shells/zsh.rs:263:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:1874:5
   5: clap_generate::generators::shells::zsh::parser_of
   6: <clap_generate::generators::shells::zsh::Zsh as clap_generate::generators::Generator>::generate
   7: <ckb_cli::subcommands::util::UtilSubCommand as ckb_cli::subcommands::CliSubCommand>::process
   8: ckb_cli::main
```

**Comment by dllud** [comment]
Still happens on ckb-cli 1.9.0

```
$ ckb-cli util completions zsh
thread 'main' panicked at /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_generate-3.0.0-beta.1/src/generators/shells/zsh.rs:263:25:
Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues
```

**Comment by eval-exec** [comment]
I'd like to work on this.
